### ISSUE TITLE
query-replace doesn't work

### ISSUE THREAD

**Issue by dkogan** [emacs-gnuplot/gnuplot#19]
gnuplot.el does something a bit too hands-on with its syntax highlighting, which breaks query-replace.

I have a plot.gp such as this:

```
plot '-' title "a", '-' title "b", '-' title "c"
```

I launch query-replace by hitting M-%. Then I try to replace all ',' with ''. After replacing the first match, gnuplot.el jumps the point past the second, so the second ',' is not replaced like it should.

**Comment by danielluehr** [comment]
Hi, 

have you ever released a new version including this patch? 
I am running the "stock" emacs' gnuplot-mode that comes with xubuntu 16.04 and the bug is still present (gnuplot.el says version 0.7.0) and bionic (current LTS) still comes with the same version.

Thanks

**Comment by dkogan** [comment]
Thanks for the ping. I never released this into Debian (and consequently into Ubuntu) because joddie never made a release tag, and I thus forgot about this. joddie: can you please tag whatever you consider to be the "good" new version?

Thanks
