### ISSUE TITLE
Move the package to a separate organization

### ISSUE THREAD

**Issue by minad** [emacs-gnuplot/gnuplot#77]
I just talked to @tarsius about packages maintained within the emacsorphanage. Since the orphanage gives the impression that a package is unmaintained I propose to move the package to a separate organization, maybe called `emacs-gnuplot`. This would involve changing the recipes in Melpa and Elpa. What do you think @mtreca? See the comment https://github.com/JonWaltman/pcmpl-args.el/issues/28#issuecomment-1022560069 by @tarsius for context. Ideally the orphanage is only used for packages which currently lack a maintainer.

**Comment by mtreca** [comment]
Creating an organization sounds like a good compromise to me, since I don't want to officially become the package maintainer but would like to still contribute alongside @conao3 (and maybe yourself?). You would be responsible for creating the organization and transferring the package there?

**Comment by minad** [comment]
Okay, I created an organization https://github.com/emacs-gnuplot and invited @mtreca and @conao3. Shall we transfer the repository there? Do you have the admin rights to start the transfer? In the next step we have to update the MELPA and NonGNU ELPA recipes.

cc @tarsius @purcell

**Comment by tarsius** [comment]
You have to temporarily invite me to the organization so that I can transfer.

**Comment by minad** [comment]
@tarsius I've sent you an invite.

**Comment by tarsius** [comment]
Transfer is done!

You should make your membership public at https://github.com/orgs/emacs-gnuplot/people.

**Comment by minad** [comment]
Thanks!

**Comment by conao3** [comment]
Thanks, I joined the organization. Recently I cannot create a spare time for Emacs community, but I'll try my best.
